Fix missing region
Fixes error (when using multivpc networks and provider overrides):
Error: cannot determine self_link for subnetwork "***": Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

  with module.slurm_controller.module.slurm_nodeset_template["debugnodeset"].module.instance_template.google_compute_instance_template.tpl,
  on modules/embedded/community/modules/internal/slurm-gcp/internal_instance_template/main.tf line 70, in resource "google_compute_instance_template" "tpl":
  70: resource "google_compute_instance_template" "tpl" {