DEMO. Deploy-time quota validation without metadata
```yaml
  ...
  modules:
  - id: network
    source: modules/network/vpc
  - id: workstation
    source: modules/compute/vm-instance
    use: [network]
    settings:
      instance_count: 2
      name_prefix: workstation
      machine_type: n2-standard-16
      disk_size_gb: 2500
```

```sh
$ ./ghpc deploy q
Testing if deployment group q/primary requires adding or changing cloud infrastructure
Error: not enough quota "Total persistent disk reserved (GB)" as "1/{project}/{region}", limit=4096 < requested=5000
not enough quota "N2 CPUs" as "1/{project}/{region}", limit=24 < requested=32
```