Allow usage of expressions in `Blueprint.Vars` and references to other `vars`. (#1563)
**NOTE**: Evaluation is happening during "expand", overwritten values (during apply) have no a effect on expressions that **used** them.

```yaml
vars:
  zone: (("${var.region}-c")) # NOT-required to be listed in topological order
  region: us-west4

vars:
  region: us-west4
  zone: us-west4-c
```

```yaml
vars:
  region: $(vars.zone)
  zone: (("${var.region}-c"))
...
Error: cyclic dependency detected: "zone" -> "region"
on line 23, column 9:
23:   zone: (("${var.region}-c"))
```

```yaml
vars:
  region: $(foo.zone)
  zone: (("${var.region}-c"))
...
Error: non-global variable "zone" referenced in expression
on line 22, column 11:
22:   region: $(foo.zone)
```