* Add `GCSBucket` to list of available detectors and getters; * Rename `GitSourceReader` -> `GoGetterSourceReader`. * Update `go-getter` dependency `v1.7.2 -> v1.7.3`
https://developer.hashicorp.com/terraform/language/modules/sources#gcs-bucket

**Usage:**
```yaml
source: gcs::https://www.googleapis.com/storage/v1/<bucket>/<path_to_module_dir>
```

**Note:**
* Doesn't support package-notation (`//`) at the bucket level,
a dir in root of the bucket is highest possible level for a package.

```sh
$ gsutil ls gs://<bucket>/dir_1/dir_2
gs://<bucket>/dir_1/dir_2/
gs://<bucket>/dir_1/dir_2/custom-image/
gs://<bucket>/dir_1/dir_2/pre-existing-vpc/
gs://<bucket>/dir_1/dir_2/vpc/
```

```yaml
---
blueprint_name: tst
vars:
  project_id:  <project>
  deployment_name: tst
  region: us-central1
deployment_groups:
- group: primary
  modules:
  - id: mod
    source: <source>

$ make && rm -rf tst && time ./ghpc create test.yaml
```

$ make && rm -rf tst && time ./ghpc create test.yaml
```

* `gcs::https://www.googleapis.com/storage/v1/<bucket>/dir_1/dir_2/vpc` _no package_
```sh
...
real    0m1.536s
$ terraform -chdir=tst/primary init
...
Downloading gcs::https://www.googleapis.com/storage/v1/<bucket>/dir_1/dir_2/vpc for mod...
- mod in .terraform/modules/mod
... # OK
```

* `gcs::https://www.googleapis.com/storage/v1/<bucket>/dir_1/dir_2/vpc/` _ends with slash_
```sh
...
real    0m1.538s
...
$ terraform -chdir=tst/primary init
...
Downloading gcs::https://www.googleapis.com/storage/v1/<bucket>/dir_1/dir_2/vpc/ for mod...
- mod in .terraform/modules/mod
... # OK
```

* `gcs::https://www.googleapis.com/storage/v1/<bucket>/dir_1//dir_2/vpc` _package_
```sh
...
real    0m2.112s
...
$ terraform -chdir=tst/primary init
...
Downloading gcs::https://www.googleapis.com/storage/v1/<bucket>/dir_1 for mod...
- mod in .terraform/modules/mod/dir_2/vpc
... # OK
$ ls tst/primary/.terraform/modules/mod/dir_2/
pre-existing-vpc  vpc
```

* `gcs::https://www.googleapis.com/storage/v1/<bucket>/dir_1//dir_2/vpc/` _package, ends with slash_
_same as above_

* `gcs::https://www.googleapis.com/storage/v1/<bucket>//dir_1/dir_2/vpc` _package separator after bucket name_
```sh
Error: failed to get module at gcs::https://www.googleapis.com/storage/v1/<bucket> to /tmp/get-module-655452250/mod: error downloading 'https://www.googleapis.com/storage/v1/<bucket>': URL is not a valid GCS URL
11:     source: gcs::https://www.googleapis.com/storage/v1/<bucket>//dir_1/dir_2/vpc
```

`go-getter` problem:

```sh
$ go-getter gcs::https://www.googleapis.com/storage/v1/<bucket>//dir_1/dir_2/vpc ~/tmp/ll
2023/10/09 23:42:36 Error downloading: URL is not a valid GCS URL
```

* `gcs::https://www.googleapis.com/storage/v1/<bucket>/missing_dir` _missing dir_
```sh
Error: lstat /tmp/get-module-2223695200/mod: no such file or directory
12:     source: gcs::https://www.googleapis.com/storage/v1/<bucket>/missing_dir
```

This is a issue with `go-getter@v1.7.2` the `DirMode` prevented raise of an error, after update to `v1.7.3` WAI:
```sh
Error: failed to get module at gcs::https://www.googleapis.com/storage/v1/<bucket>/missing_dir to /tmp/get-module-3980916664/mod: storage: object doesn't exist
12:     source: gcs::https://www.googleapis.com/storage/v1/<bucket>/missing_dir
```

* `wut::kpss://wrong_protocol` _wrong protocol_
```sh
Error: failed to get module at wut::kpss://wrong_protocol to /tmp/get-module-3977420508/mod: download not supported for scheme 'wut'
12:     source: wut::kpss://wrong_protocol
                ^
real    0m0.070s
```

```yaml
---
blueprint_name: tst
vars:
  project_id:  <project>
  deployment_name: tst
deployment_groups:
- group: primary
  modules:
  - id: mod
    kind: packer
    source: <source>
    settings:
      subnetwork_name: any
      zone: danger

$ make && rm -rf tst && time ./ghpc create test.yaml
```

* `gcs::https://www.googleapis.com/storage/v1/<bucket>/dir_1/dir_2/custom-image` _no package_
```sh
real    0m2.002s # OK
$ tree tst/primary/
tst/primary/
└── mod # + hcl files
```

* `gcs::https://www.googleapis.com/storage/v1/<bucket>/dir_1//dir_2/custom-image` _package_
```sh
real    0m4.980s # OK

$ tree tst/primary/mod/
tst/primary/mod/
└── dir_2
    ├── custom-image     # + hcl files
    ├── pre-existing-vpc # + tf files
    └── vpc              # + tf files
```

* _missing dir & wrong protocol_ yield the same result as Terraform test cases; WAI.