Selectevly suggest to run `ghpc export-outputs`
```sh
$ ./ghpc deploy tst
Testing if deployment group tst/primary requires adding or changing cloud infrastructure
Error: terraform plan for deployment group tst/primary failed; run "ghpc export-outputs" on previous deployment groups to define inputs
exit status 1

Error: No value for required variable

  on variables.tf line 32:
  32: variable "region" {

The root module input variable "region" is not set, and has no default value.
Use a -var or -var-file command line argument to provide a value for this
variable.

...

$ ./ghpc deploy tst
Testing if deployment group tst/primary requires adding or changing cloud infrastructure
Error: terraform plan for deployment group tst/primary failed
exit status 1

Error: Invalid value for variable

  on main.tf line 20, in module "network":
  20:   network_address_range = "over the hills and far away"
    ├────────────────
    │ var.network_address_range is "over the hills and far away"

IP address range must be in CIDR format.

This was checked by the validation rule at
modules/embedded/modules/network/vpc/variables.tf:65,3-13.
```