Use self_link for subnetwork instead of name.
This helps avoid errors like:
Error: cannot determine self_link for subnetwork "***": Cannot determine region:
set in this resource, or set provider-level 'region' or 'zone'.