Improve error logging for expressions parsing
* Show snippet with ponter to a column;

```sh
Error: :0,21-22: Invalid character; This character is not used within the language., and 1 other diagnostic(s)
34:         content: |

Error: Invalid character; This character is not used within the language.
  echo "Hello $(vars.project_id from $(vars.region)"
                                     ^
33:         content: |
```

* Prevent line-breaks within expressions.
This constraint existed before, but was accidentaly relaxed by recent PR.