Refactor `validateConfig`
* Move `validateModule` before "expand";
* Collect all errors to output;

```yaml
vars:
  region: # do not forget to set

deployment_groups:
- group: primary
  modules:
  - id: arbuz
    source: ./arbus_store

  - id: nw2
    source: modules/network/vpc
    settings:
      kill.switch: $(wut.this)
      green: $(arbuz.gold)
      orange: $(vars.yarn)
    outputs: [gold, silver]
```

```shell
**************** building ghpc ************************
deployment_name input error, cause: Could not find source of variable

Error: blueprint_name input error, cause: value is an empty string
16: vars:
    ^

Error: deployment variable region was not set
17:   region: # do not forget to set
             ^

Error: failed to get info using tfconfig for terraform module at ./arbus_store: Source to module does not exist: ./arbus_store
23:     source: ./arbus_store
                ^

Error: a setting was added that is not found in the module
30:       green: $(arbuz.gold)
                 ^

Error: a setting name contains a period, which is not supported; variable subfields cannot be set independently in a blueprint.
29:       kill.switch: $(wut.this)
                       ^

Error: a setting was added that is not found in the module
31:       orange: $(vars.yarn)
                  ^

Error: requested output was not found in the module, module: nw2 output: gold
32:     outputs: [gold, silver]
                  ^

Error: requested output was not found in the module, module: nw2 output: silver
32:     outputs: [gold, silver]
                        ^

Error: invalid module reference: wut
29:       kill.switch: $(wut.this)
                       ^

Error: module "nw2" references unknown global variable "yarn"
31:       orange: $(vars.yarn)
                  ^

Error: failed to get info using tfconfig for terraform module at ./arbus_store: Source to module does not exist: ./arbus_store
30:       green: $(arbuz.gold)
                 ^
```