Point path of mapping item to key instead of value position
Currently error path points to a "value" part of key value path `Root.Group.At(i).Modules.At(j).Settings.Dot("scheduling")`.

Example of problem:

```yaml
  settings:
    scheduling:
      maintenanceInterval: "PERIODIC"
```

Error:
```sh
Error: a setting was added that is not found in the module
200:         maintenanceInterval: "PERIODIC"
```

After fix:
```sh
Error: a setting was added that is not found in the module
199:       scheduling:
```